#!/bin/bash

trap "echo '*** Last command failed'; exit 1" ERR INT TERM QUIT

COUNT=0

for Z in 0 6; do
    for COMPRESSION_ALGO in Uncompressed ZIP ZLIB BZIP2; do
        for CIPHER in AES; do
            for HASH in SHA1; do
                for S2K_MODE in 0 1 3; do
                    for S2K_COUNT in 1024; do
                        for MDC_MODE in "--force-mdc" "--disable-mdc"; do
                            echo "NieMo2liuvoh2iighee3oo" | gpg -v -z ${Z} \
                                --passphrase-fd 0 --batch --yes --no-tty \
                                --compression-algo ${COMPRESSION_ALGO} \
                                --cipher-algo ${CIPHER} \
                                --digest-algo ${HASH} \
                                --s2k-mode ${S2K_MODE} \
                                --s2k-count ${S2K_COUNT} \
                                --default-key D5B89C4C \
                                --sign \
                                ${MDC_MODE} \
                                -o workdir/corpus/`printf "%05d" $COUNT`.gpg \
                                -c plain.txt
                            
                            COUNT=$[$COUNT + 1]
                         done
                     done
                 done
             done
          done
     done
done
                            
